name: bigbucks
description: A way to get track of money lent and borrowed.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  flutter_riverpod: ^1.0.4
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  firebase_storage: ^10.3.7
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  image_picker: ^0.8.5+3
  enough_giphy_flutter: ^0.3.0
  intl: ^0.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
  image_path_android: "assets/images/bigmoni.png"
  image_path_ios: "assets/images/bigmoni.png"
  remove_alpha_ios: true
flutter:
  uses-material-design: true

  assets:
     - assets/images/bigmoni.png
     - assets/images/user.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700