name: Android app Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        name: Build APK and Create release
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
            - run: flutter pub get

            - name: Create APK
              run: |
                  flutter build apk --split-per-abi
                  mkdir Release
                  mv build/app/outputs/apk/release/*.apk Release/

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  prerelease: true
                  body: Testing this app
                  files: |
                      Release/app-arm64-v8a-release.apk
                      Release/app-armeabi-v7a-release.apk
                      Release/app-x86_64-release.apk
